settings:
  database:
    driver: mysql
    source: root:123456@tcp(127.0.0.1:3306)/access_control?charset=utf8&parseTime=True&loc=Local&timeout=1000ms
#    source: root:123456@tcp(127.0.0.1:3306)/
  cache:
    redis:
      addr: 127.0.0.1:6379
      password:
      db: 1
    memory: ''
